project_id = "prabha-yogashala"

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[api]
max_rows = 1000

[auth]
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://localhost:3000/**", "http://127.0.0.1:3000/**"]
