import type { Metadata } from "next";

import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { Card } from "@/components/ui/card";
import { BUSINESS_TIME_ZONE, BUSINESS_TIME_ZONE_LABEL } from "@/lib/dates";
import { siteConfig } from "@/config/site";

export const metadata: Metadata = { title: "Settings" };

export default function AdminSettingsPage() {
  return <div className="space-y-10"><AdminPageHeader eyebrow="Configuration" title="Settings" description="The current schema has no persisted settings model. This page reports the verified configuration sources and does not present controls that cannot save truthfully." /><section className="grid gap-4 md:grid-cols-2"><Card><h2 className="font-display text-2xl font-medium text-brand-strong">Business timezone</h2><p className="mt-3 font-semibold text-brand-strong">{BUSINESS_TIME_ZONE_LABEL}</p><p className="mt-1 text-sm text-muted">{BUSINESS_TIME_ZONE}</p><p className="mt-4 text-sm leading-6 text-muted">Admin date/time inputs use this fixed V1 timezone; scheduled instants are stored as UTC.</p></Card><Card><h2 className="font-display text-2xl font-medium text-brand-strong">Business identity</h2><p className="mt-3 font-semibold text-brand-strong">{siteConfig.name}</p><p className="mt-4 text-sm leading-6 text-muted">Name, WhatsApp number, broad availability windows, and public navigation remain code-reviewed configuration rather than editable database settings.</p></Card><Card><h2 className="font-display text-2xl font-medium text-brand-strong">Booking policy</h2><p className="mt-3 text-sm leading-6 text-muted">Customers may cancel their own future pending or confirmed booking. Refunds, rescheduling, payment rules, and late-cancellation policy remain unconfirmed and are not configurable.</p></Card><Card><h2 className="font-display text-2xl font-medium text-brand-strong">Email delivery</h2><p className="mt-3 text-sm leading-6 text-muted">Custom production SMTP remains an external account/configuration blocker. This portal does not bypass email confirmation or expose provider credentials.</p></Card></section><section className="rounded-2xl border border-dashed border-brand/25 bg-surface-subtle p-6 sm:p-8"><h2 className="font-display text-2xl font-medium text-brand-strong">Why controls are deferred</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-muted">Adding editable settings without a schema, validation rules, access policy, audit requirements, and approved business values would create a second source of truth. A future milestone should add that model only after those requirements are confirmed.</p></section></div>;
}
